Repository pimcore/customer-data-framework, pull requests merged in 2020-04, with the labels that each got.

#160 get last response from request
  src/Newsletter/ProviderHandler/Mailchimp/CustomerExporter/AbstractExporter.php
Labels: Improvement

#159 [Routing] Change routing annotations to core Symfony
  src/Controller/Admin/GDPRDataController.php
  src/Controller/Rest/Api/DeletionsController.php
  src/Controller/Rest/Api/SegmentsOfCustomersController.php
  src/Controller/Rest/CrudHandlerController.php
  src/Controller/Rest/Mailchimp/WebhookController.php
  src/Controller/Rest/Newsletter/AdminController.php
Labels: Bug

#157 Fix custom report adapter namespace as per psr-4 autoloading standards
  src/CustomReport/Adapter/TermSegmentBuilder.php
  src/Resources/config/services.yml
Labels: Task

#161 Display the consent values as checkbox not as their class names.
  src/View/Formatter/DefaultViewFormatter.php
Labels: Improvement
