Repository pimcore/customer-data-framework, pull requests merged in 2021-05, with the labels that each got.

#217 Cast querybuilder to string when fetching data
  src/ActionTrigger/Queue/DefaultQueue.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
Labels: Bug

#214 Upgrade box/spout Version
  composer.json
  src/CustomerList/Exporter/Xlsx.php
Labels: Task

#207 Validate after applying save handlers
  src/CustomerSaveManager/DefaultCustomerSaveManager.php
Labels: Bug

#211 Add customer language - #78
  doc/02_Installation/README.md
  install/class_source/optional/class_Customer_export.json
  src/Model/CustomerInterface.php
  src/Model/Traits/CustomerTrait.php
  src/Newsletter/ProviderHandler/Mailchimp.php
Labels: Improvement
