Repository pimcore/customer-data-framework, pull requests merged in 2021-03, with the labels that each got.

#170 [Activities] Restore activity meta-data storage
  src/ActivityStore/MariaDb.php
  src/ActivityStore/SqlActivityStore.php
Labels: Bug

#103 Added support for Mailchimps multi-value merge-field ADDRESS.
  doc/03_Configuration.md
  src/Newsletter/ProviderHandler/Mailchimp.php
  src/Newsletter/ProviderHandler/Mailchimp/DataTransformer/Address.php
Labels: New Feature

#177 Support for Primary-Replica Db connection
  src/Model/CustomerView/FilterDefinition/Dao.php
  src/Model/CustomerView/FilterDefinition/Listing/Dao.php
  src/SegmentAssignment/Indexer/Indexer.php
  src/SegmentAssignment/QueueBuilder/DefaultQueueBuilder.php
  src/SegmentAssignment/SegmentAssigner/SegmentAssigner.php
Labels: Bug

#188 Update Pimcore dependency
  README.md
  composer.json
  doc/02_Installation/01_Update.md
  doc/02_Installation/README.md
  doc/18_Single_Sign_On.md
Labels: Task

#187 Fixed command deprecations
  src/ActionTrigger/EventHandler/DefaultEventHandler.php
  src/Command/AbstractCommand.php
  src/Command/ActionTriggerQueueCommand.php
  src/Command/BuildSegmentsCommand.php
  src/Command/CronTriggerCommand.php
  src/Command/DuplicatesIndexCommand.php
  src/Command/MaintenanceCommand.php
  src/Command/NewsletterSyncCommand.php
  src/Command/SegmentAssignmentIndexCommand.php
  src/Resources/config/services.yml
  src/Resources/config/services_events.yml
Labels: Task

#189 Fixed controller deprecations
  frontend-samples/sso_client/src/AppBundle/Controller/ContentController.php
  src/Controller/Admin.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
Labels: Task

#191 Switched to Settingsstore Aware Installer
  doc/02_Installation/01_Update.md
  src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
  src/Installer.php
  src/Migrations/PimcoreX/Version20210305134111.php
  src/Migrations/Version20210305134111.php
  src/Resources/config/doctrine_migrations.yml
  src/Resources/config/services.yml
Labels: Task

#192 [Models] Add type hints to customer interfaces
  doc/02_Installation/01_Update.md
  src/Model/CustomerInterface.php
  src/Model/CustomerSegmentInterface.php
  src/Model/SsoAwareCustomerInterface.php
  src/Model/SsoIdentityInterface.php
Labels: BC-BREAK, Task

#193 Refactored and fixed SearchQuery filter
  doc/02_Installation/01_Update.md
  src/CustomerList/Filter/SearchQuery.php
  src/CustomerList/SearchHelper.php
  src/Listing/Filter/BoolCombinator.php
  src/Listing/Filter/QueryConditionFilterInterface.php
  src/Listing/FilterHandler.php
  tests/Model/Customer/CustomerListTest.php
  tests/Model/Customer/CustomerTest.php
Labels: BC-BREAK, Bug, Improvement

#194 [Activity Store] Bugfixing
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
  src/Model/ActivityStoreEntry/DefaultActivityStoreEntry.php
  src/Service/MariaDb.php
  tests/Model/Activity/ActivityTest.php
Labels: Bug

#196 Fixed event dispatcher params
  composer.json
  src/ActivityManager/DefaultActivityManager.php
  src/Event/TargetingEventListener.php
  src/Newsletter/ProviderHandler/Mailchimp/TemplateExporter.php
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
  src/Targeting/SegmentTracker.php
Labels: Task

#195 Query builder migration
  composer.json
  src/ActionTrigger/Queue/DefaultQueue.php
  src/ActivityStore/MariaDb.php
  src/ActivityStore/MySQL.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/Controller/Admin/DuplicatesController.php
  src/CustomerList/Filter/CustomerSegment.php
  src/CustomerList/Filter/SearchQuery.php
  src/CustomerList/SearchHelper.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/DuplicatesIndex/DuplicatesIndexInterface.php
  src/Listing/Filter/AbstractFieldBetween.php
  src/Listing/Filter/AbstractFieldValue.php
  src/Listing/Filter/BoolCombinator.php
  src/Listing/Filter/OnCreateQueryFilterInterface.php
  src/Listing/Filter/Permission.php
  src/Listing/FilterHandler.php
  src/Listing/FilterInterface.php
  src/Model/ActivityList/ActivityListInterface.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
  src/Newsletter/ProviderHandler/Mailchimp.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
  src/Resources/config/services.yml
  src/Resources/views/Admin/Duplicates/list.html.php
  src/Resources/views/Admin/Duplicates/partials/list-filter.html.php
  src/Resources/views/Admin/Partial/Table/pagination-footer.html.php
  src/Security/SsoIdentity/DefaultSsoIdentityService.php
  src/Templating/Helper/FilterFormAction.php
  src/Templating/Helper/FormOrderParams.php
Labels: BC-BREAK, Task

#197 Migrate paginator to KnpPaginatorBundle
  src/ActionTrigger/EventHandler/DefaultEventHandler.php
  src/ActivityStore/ActivityStoreInterface.php
  src/ActivityStore/MariaDb.php
  src/ActivityStore/MySQL.php
  src/ActivityStore/SqlActivityStore.php
  src/Controller/Admin.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/Model/ActivityList/DefaultMariaDbActivityList.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
  src/Pimcore/Model/Tool/ListingAdapter.php
  src/RESTApi/AbstractHandler.php
  src/RESTApi/CustomersHandler.php
  src/RESTApi/SegmentGroupsHandler.php
  src/RESTApi/SegmentsHandler.php
  src/Resources/views/Admin/Activities/list.html.php
  src/Resources/views/Admin/Customers/list.html.php
  src/Resources/views/Admin/Customers/partials/list-table.html.php
  src/Resources/views/Admin/Partial/Table/pagination-footer.html.php
  src/SegmentBuilder/AbstractSegmentBuilder.php
  src/SegmentBuilder/AgeSegmentBuilder.php
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
Labels: BC-BREAK, Task
