Repository pimcore/customer-data-framework, pull requests merged in 2022-10, with the labels that each got.

#339 Codeception/Symfony: Fix deprecations
  phpstan-baseline.neon
  src/Command/ActionTriggerQueueCommand.php
  src/Command/BuildSegmentsCommand.php
  src/Command/CronTriggerCommand.php
  src/Command/DuplicatesIndexCommand.php
  src/Command/MaintenanceCommand.php
  src/Command/SegmentAssignmentIndexCommand.php
  src/Controller/Rest/AbstractRestController.php
  src/DependencyInjection/Configuration.php
  src/Event/Frontend/UrlActivityTracker.php
  src/Installer.php
  src/Model/ActionTrigger/Rule/Listing.php
  src/Model/ActionTrigger/Rule/Listing/Dao.php
  src/Model/ActivityList/DefaultMariaDbActivityList.php
  src/Model/CustomerInterface.php
  src/Model/CustomerView/FilterDefinition/Listing.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
  src/Security/Guard/WebserviceAuthenticator.php
  src/Security/UserProvider/CustomerObjectUserProvider.php
  src/Targeting/EventListener/ElementSegmentsListener.php
  src/Targeting/EventListener/TargetingToolbarListener.php
Labels: Bug

#348 [Actions] register bundles through bundles.php
  .github/ci/files/config/bundles.php
  .github/ci/files/extensions.template.php
  .github/ci/scripts/setup-environment.sh
Labels: Task

#350 [Task]: Change the `force` parameter as array to be compatible with Pimcore 11 changes
  src/CustomerProvider/DefaultCustomerProvider.php
Labels: Task

#344 Remove support for old authentication system
  .github/ci/files/config/packages/security.yaml
  composer.json
  doc/19_SSO_Flows.md
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/security.yml
  src/Controller/Admin/SettingsController.php
  src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
  src/Resources/config/pimcore/config.yml
  src/Resources/config/services_security.yml
  src/Resources/config/services_security_webservice.yml
  src/Resources/config/services_security_webservice_legacy.yml
  src/Security/Guard/WebserviceAuthenticator.php
Labels: Task, BC-BREAK

#347 Fix Twig deprecations
  src/Twig/Extension/CmfFrontendUtilsExtension.php
  src/Twig/Extension/CmfUrlUtilsExtension.php
Labels: Bug
