Repository pimcore/customer-data-framework, pull requests merged in 2022-11, with the labels that each got.

#351 Fix PhpStan errors
  composer.json
  phpstan-baseline.neon
  src/DataSimilarityMatcher/DataSimilarityMatcherInterface.php
  src/DataSimilarityMatcher/SimilarText.php
  src/Security/SsoIdentity/DefaultSsoIdentityService.php
  src/SegmentAssignment/StoredFunctions/DefaultStoredFunctions.php
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
Labels: Bug

#354 Added translations and proper translation key names for errors
  src/Resources/public/js/config/panel.js
  src/Resources/translations/admin.de.yml
  src/Resources/translations/admin.en.yml
Labels: Bug

#359 Remove hwi bundle and SSO implementation
  README.md
  composer.json
  doc/01_Architecture-Overview.md
  doc/02_Installation/01_Update.md
  doc/02_Installation/README.md
  doc/03_Configuration.md
  doc/18_Single_Sign_On.md
  doc/19_SSO_Flows.md
  frontend-samples/sso_client/README.md
  frontend-samples/sso_client/app/Resources/views/Auth/login.html.php
  frontend-samples/sso_client/app/Resources/views/Auth/partials/social-login-buttons.html.php
  frontend-samples/sso_client/app/Resources/views/Auth/register.html.php
  frontend-samples/sso_client/app/Resources/views/Content/secure.html.php
  frontend-samples/sso_client/app/Resources/views/Form/Theme/Bootstrap/form_row.html.php
  frontend-samples/sso_client/app/Resources/views/Layout/layout.html.php
  frontend-samples/sso_client/src/AppBundle/AppBundle.php
  frontend-samples/sso_client/src/AppBundle/Controller/AuthController.php
  frontend-samples/sso_client/src/AppBundle/Controller/ContentController.php
  frontend-samples/sso_client/src/AppBundle/DependencyInjection/AppExtension.php
  frontend-samples/sso_client/src/AppBundle/Form/LoginFormType.php
  frontend-samples/sso_client/src/AppBundle/Form/RegistrationFormHandler.php
  frontend-samples/sso_client/src/AppBundle/Form/RegistrationFormType.php
  frontend-samples/sso_client/src/AppBundle/Model/Customer.php
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/config.yml
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/routing.yml
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/security.yml
  frontend-samples/sso_client/src/AppBundle/Resources/config/services.yml
  phpstan-baseline.neon
  src/DependencyInjection/Compiler/OAuthUtilsPass.php
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/Resources/config/services_security.yml
  src/Resources/config/services_security_oauth_client.yml
  src/Security/OAuth/AccountConnector.php
  src/Security/OAuth/AccountConnectorInterface.php
  src/Security/OAuth/Exception/AccountNotLinkedException.php
  src/Security/OAuth/OAuthRegistrationHandler.php
  src/Security/OAuth/OAuthUtils.php
  src/Security/OAuth/SessionTokenStorage.php
  src/Security/OAuth/TokenStorageInterface.php
  src/Security/SsoIdentity/DefaultSsoIdentityService.php
  src/Security/UserProvider/OAuthAwareUserProvider.php
Labels: Task, BC-BREAK

#356 Use class resolver to resolve dependencies instead of injecting `ContainerInterface` which is deprecated
  src/Model/ClassDefinition/Helper/UserCheckerClassResolver.php
  src/Resources/config/services_security.yml
  src/Security/Authentication/LoginManager.php
Labels: Task, BC-BREAK

#353 Symfony 6 upgrades
  composer.json
  src/Model/AbstractCustomer/DefaultAbstractUserawareCustomer.php
  src/Model/Traits/DefaultUserawareCustomerTrait.php
  src/Security/Authenticator/WebserviceAuthenticator.php
  src/Security/UserProvider/CustomerObjectUserProvider.php
Labels: Task, BC-BREAK

#365 Symfony 6 upgrades - follow up to #353
  composer.json
  src/Controller/Admin/SegmentAssignmentController.php
  src/Controller/Rest/AbstractRestController.php
Labels: Task

#366 Update README for SSO
  README.md
Labels: Task

#360 [Tests] Add support for codeception 5
  .github/workflows/codeception.yml
  codeception.dist.yml
  composer.json
  doc/02_Installation/01_Update.md
  tests/Model.suite.yml
  tests/Model/Activity/ActivityTest.php
  tests/Model/Customer/CustomerListTest.php
  tests/Model/Customer/CustomerTest.php
  tests/Support/Fixtures/View/Formatter/NoToStringObject.php
  tests/Support/Fixtures/View/Formatter/ToStringObject.php
  tests/Support/Helper/Model.php
  tests/Support/Helper/Unit.php
  tests/Support/ModelTester.php
  tests/Support/UnitTester.php
  tests/Unit.suite.dist.yml
  tests/Unit/DataTransformer/Zip2StateTest.php
  tests/Unit/DataTransformer/ZipTest.php
  tests/Unit/SegmentAssignment/TypeMapper/TypeMapperTest.php
  tests/Unit/View/Formatter/ObjectWrapperTest.php
  tests/_bootstrap.php
Labels: Task

#369 Add support for Pimcore 10 & 11
  .github/ci/files/config/packages/doctrine_migrations.yaml
  .github/workflows/codeception.yml
  codeception.dist.yml
  composer.json
  src/Model/Traits/DefaultUserawareCustomerTrait.php
  src/Security/UserProvider/CustomerObjectUserProvider.php
  tests/Model.suite.yml
  tests/Model/Activity/ActivityTest.php
  tests/Model/Customer/CustomerListTest.php
  tests/Model/Customer/CustomerTest.php
  tests/Unit.suite.dist.yml
  tests/Unit/DataTransformer/Zip2StateTest.php
  tests/Unit/DataTransformer/ZipTest.php
  tests/Unit/SegmentAssignment/TypeMapper/TypeMapperTest.php
  tests/Unit/View/Formatter/ObjectWrapperTest.php
  tests/_bootstrap.php
  tests/_support/Helper/Model.php
Labels: Task

#362 Deprecate SSO functionality
  README.md
  doc/01_Architecture-Overview.md
  doc/02_Installation/01_Update.md
  doc/02_Installation/README.md
  doc/03_Configuration.md
  doc/18_Single_Sign_On.md
  doc/19_SSO_Flows.md
  frontend-samples/sso_client/README.md
  frontend-samples/sso_client/app/Resources/views/Auth/partials/social-login-buttons.html.php
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/config.yml
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/routing.yml
  frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/security.yml
  src/Resources/config/services_security.yml
  src/Resources/config/services_security_oauth_client.yml
  src/Security/OAuth/AccountConnector.php
  src/Security/OAuth/AccountConnectorInterface.php
  src/Security/OAuth/Exception/AccountNotLinkedException.php
  src/Security/OAuth/OAuthRegistrationHandler.php
  src/Security/OAuth/OAuthUtils.php
  src/Security/OAuth/SessionTokenStorage.php
  src/Security/OAuth/TokenStorageInterface.php
  src/Security/SsoIdentity/DefaultSsoIdentityService.php
  src/Security/UserProvider/OAuthAwareUserProvider.php
Labels: Task

#345 [Task]: Quoting fields in actiontrigger_rules, activities_metadata
  .github/workflows/static-analysis.yml
  phpstan-lowest.neon
  src/ActivityStore/MariaDb.php
  src/ActivityStore/SqlActivityStore.php
  src/Model/ActionTrigger/Rule/Dao.php
Labels: Task

#375 Fix: paginator total count
  src/RESTApi/ActivitiesHandler.php
Labels: Bug

#374 [Task]: Apply native parameter and return type hints
  install/class_source/class_CustomerSegmentGroup_export.json
  install/class_source/class_CustomerSegment_export.json
  install/class_source/class_LinkActivityDefinition_export.json
  install/class_source/class_SsoIdentity_export.json
  install/class_source/class_TermSegmentBuilderDefinition_export.json
  install/class_source/optional/class_Customer_export.json
  install/objectbrick_source/objectbrick_OAuth1Token_export.json
  install/objectbrick_source/objectbrick_OAuth2Token_export.json
  src/ActionTrigger/RuleEnvironment.php
  src/Controller/Rest/AbstractRestController.php
  src/CustomReport/Adapter/TermSegmentBuilder.php
  src/Installer.php
  src/Model/ActionTrigger/Rule/Listing.php
  src/Model/ActionTrigger/Rule/Listing/Dao.php
  src/Model/ActivityList/ActivityListInterface.php
  src/Model/ActivityList/DefaultMariaDbActivityList.php
  src/Model/CustomerView/FilterDefinition/Dao.php
  src/Model/CustomerView/FilterDefinition/Listing.php
  src/Model/CustomerView/FilterDefinition/Listing/Dao.php
  src/Newsletter/AddressSource/SegmentAddressSource.php
  src/Targeting/Condition/CustomerIsLoggedIn.php
  src/Targeting/Condition/CustomerSegmentsHaveChanged.php
  src/Targeting/Condition/HasSegment.php
Labels: Task, BC-BREAK

#377 [Task]: Bump pimcore version to 10.6
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: Task
