Repository pimcore/customer-data-framework, pull requests merged in 2022-09, with the labels that each got.

#327 Support Doctrine DBAL V3
  .github/ci/scripts/setup-environment.sh
  composer.json
  src/ActivityStore/MariaDb.php
  src/ActivityStore/MySQL.php
  src/ActivityStore/SqlActivityStore.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/Model/ActionTrigger/ActionDefinition/Dao.php
  src/Model/ActionTrigger/Rule/Dao.php
  src/Model/ActivityList/DefaultMariaDbActivityList.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
  src/Model/CustomerView/FilterDefinition/Dao.php
  src/Newsletter/ProviderHandler/Mailchimp/MailChimpExportService.php
  src/SegmentManager/DefaultSegmentManager.php
  tests/Model/Customer/CustomerListTest.php
Labels: Task

#331 Fix: DBAL Deprecations - follow up to #320
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
Labels: Bug

#322 Added unit tests for exact search query
  tests/Model/Customer/CustomerListTest.php
Labels: Task

#328 Migrate MaintenanceEventListener to Maintenance Tasks
  phpstan-baseline.neon
  src/Maintenance/Tasks/CleanupEmptyFoldersTask.php
  src/Maintenance/Tasks/CleanupExportTmpDataTask.php
  src/Resources/config/services.yml
  src/Resources/config/services_events.yml
Labels: Bug

#330 Fixed autosave not preserving versions issue
  src/Event/PimcoreObjectEventListener.php
Labels: Bug

#337 Fix codeception tests
  .github/ci/scripts/setup-environment.sh
  .github/workflows/codeception.yml
Labels: Bug

#335 Replace box/spout abandoned package with openspout/openspout
  composer.json
  src/CustomerList/Exporter/Xlsx.php
Labels: Task

#318 Replaced plugin with event listeners
  composer.json
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/Resources/public/js/events.js
  src/Resources/public/js/startup.js
Labels: Improvement

#333 Removed deprecated boolean return value
  src/Model/CustomerInterface.php
Labels: Task, BC-BREAK

#336 Avoid usage of deprecated Document::$types
  src/SegmentAssignment/TypeMapper/TypeMapper.php
Labels: Task

#341 Replace childs with children
  install/class_source/class_CustomerSegmentGroup_export.json
  install/class_source/class_CustomerSegment_export.json
  install/class_source/class_LinkActivityDefinition_export.json
  install/class_source/class_SsoIdentity_export.json
  install/class_source/class_TermSegmentBuilderDefinition_export.json
  install/class_source/optional/class_Customer_export.json
  install/objectbrick_source/objectbrick_OAuth1Token_export.json
  install/objectbrick_source/objectbrick_OAuth2Token_export.json
Labels: Task
