Repository pimcore/customer-data-framework, pull requests merged in 2022-07, with the labels that each got.

#299 Pimcore X provides TargetGroup Object in Action Array
  src/Targeting/ActionHandler/AssignTargetGroupAndSegment.php
Labels: Bug

#306 Fix phpstan issue: ocramius/package-versions contains a Composer plug…
  composer.json
Labels: Bug

#308 Bump pimcore/pimcore version to 10.5
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/app/AppKernel.php
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/doctrine_migrations.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/packages/test/config.yaml
  .github/ci/files/config/routes/test/routes.yaml
  .github/ci/files/config/services.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
  .github/ci/pimcore_6_9/files/.my.cnf
  .github/ci/pimcore_6_9/files/app/config/config.yml
  .github/ci/pimcore_6_9/files/app/config/config_dev.yml
  .github/ci/pimcore_6_9/files/app/config/config_test.yml
  .github/ci/pimcore_6_9/files/app/config/parameters.example.yml
  .github/ci/pimcore_6_9/files/app/config/routing_dev.yml
  .github/ci/pimcore_6_9/files/app/config/services.yml
  .github/ci/pimcore_6_9/files/app/config/system.yml
  .github/ci/pimcore_6_9/files/web/.htaccess
  .github/ci/pimcore_6_9/files/web/app_test.php
  .github/ci/pimcore_x/files/config/routes/test/routes.yaml
  .github/ci/scripts/setup-environment.sh
  .github/ci/scripts/setup-pimcore-6-9-environment.sh
  .github/ci/scripts/setup-pimcore-x-environment.sh
  .github/workflows/codeception.yml
  .github/workflows/codeception_pimcore_6_9.yml
  .github/workflows/static-analysis-pimcore-6-9.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpstan-pimcore-6-9.neon
  phpstan.neon
  src/Installer.php
  src/Migrations/Version20171019130865.php
  src/Migrations/Version20171102160547.php
  src/Migrations/Version20171113110855.php
  src/Migrations/Version20171207150300.php
  src/Migrations/Version20171218194028.php
  src/Migrations/Version20180102103153.php
  src/Migrations/Version20180410085629.php
  src/Migrations/Version20210305134111.php
  src/Migrations/Version20220316141955.php
  src/Model/CustomerInterface.php
  src/Model/CustomerSegmentInterface.php
  stubs/AbstractListing.stub
  stubs/AbstractObject.stub
  stubs/ElementEventInterface.stub
  stubs/ElementInterface.stub
  stubs/TargetGroup.stub
  stubs/TokenInterface.stub
  stubs/UserInterface.stub
Labels: Task

#270 Remove laminas/laminas-zendframework-bridge again
  composer.json
Labels: Improvement

#240 Fix: Not setting the attribute "package" of the "deprecated" option is deprecated.
  src/Resources/config/services.yml
  src/Resources/config/services_events.yml
  src/Resources/config/services_security.yml
  src/Resources/config/services_security_webservice_legacy.yml
Labels: Task

#302 Replaced deprecated Pimcore\Cache\Runtime with Pimcore\Cache\RuntimeCache
  src/Model/ActionTrigger/ActionDefinition.php
  src/Model/ActionTrigger/Rule.php
  src/Model/CustomerView/FilterDefinition.php
  src/Newsletter/ProviderHandler/Mailchimp/MailChimpExportService.php
  src/SegmentManager/SegmentMerger/DefaultSegmentMerger.php
Labels: Task
