Repository pimcore/customer-data-framework, pull requests merged in 2023-01, with the labels that each got.

#387 [Task]: Replace error suppressed elvis operator in favor of null coalesce
  src/Controller/Admin/CustomersController.php
Labels: Task

#386 [Bug] Fixing creationDate
  src/Model/ActionTrigger/Rule/Dao.php
Labels: Bug

#389 [Improvement]: Add primary key to `plugin_cmf_deletions` table
  CHANGELOG.md
  src/Installer.php
  src/Migrations/PimcoreX/Version20221229215900.php
Labels: Improvement, BC-BREAK

#394 Fixed types actions
  .github/workflows/codeception.yml
  src/Controller/Rest/AbstractRestController.php
Labels: Bug

#395 Return type fixes
  phpstan-baseline.neon
  src/Controller/Admin.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/GDPR/DataProvider/Customers.php
  src/Installer.php
  src/Model/SegmentAssignment/SegmentAssignment/Dao.php
  src/Targeting/ActionHandler/ApplyTargetGroupsFromSegments.php
  src/Targeting/ActionHandler/AssignTargetGroupAndSegment.php
  src/Targeting/ActionHandler/TrackActivity.php
  src/Targeting/ActionHandler/TrackSegment.php
  src/Targeting/DataProvider/Customer.php
  src/Targeting/DataProvider/CustomerSegments.php
Labels: Task

#399 [Task]: Bump Number Sequence Generator to v2 (support for Pimcore 10.6 & 11)
  composer.json
Labels: Task

#401 [Task]: Implement `searchData` method in `Customers` data provider
  src/GDPR/DataProvider/Customers.php
Labels: Task

#405 Doc fixes
  doc/01_Architecture-Overview.md
  doc/02_Installation/README.md
  doc/04_Cronjobs.md
  doc/09_Activities/README.md
  doc/22_ActionTrigger.md
Labels: Task

#404 Move custom reports config to prepend extension
  phpstan-lowest.neon
  phpstan.neon
  src/CustomReport/Adapter/TermSegmentBuilder.php
  src/CustomReport/Adapter/TermSegmentBuilderBase.php
  src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
  src/Resources/config/custom_reports.yaml
  src/Resources/config/custom_reports_legacy.yml
  src/Resources/config/pimcore/config.yml
  src/Resources/config/services.yml
  src/Resources/public/js/pimcore/report/custom/definitions/termSegmentBuilder.js
  tests/_support/Helper/Model.php
Labels: Task
