Repository pimcore/customer-data-framework, pull requests merged in 2023-04, with the labels that each got.

#441 [Task] Change service injection to autowire
  src/Newsletter/ProviderHandler/Mailchimp/UpdateFromMailchimpProcessor.php
Labels: Task

#447 [Bug]: Fix PHPstan.
  phpstan-baseline.neon
Labels: Bug

#434 Activity List class incompatibility fix with return type
  phpstan-baseline.neon
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
Labels: Bug

#450 Remove newsletter config - follow up to #1
  .github/ci/files/config/system.yml
Labels: sync

#452 [Task] Update requirements in composer.json
  composer.json
  src/PimcoreCustomerManagementFrameworkBundle.php
Labels: Task

#453 [Security] Embeding untrusted input inside CSV files leads to Formula Injection/CSV Injection
  src/CustomerList/Exporter/AbstractExporter.php
Labels: Bug, Security

#454 Adapt admin bundle refactoring
  .github/ci/files/config/bundles.php
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  composer.json
  src/Controller/Admin.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/Customers/FilterDefinitionController.php
  src/Controller/Admin/CustomersController.php
  src/Controller/Admin/DuplicatesController.php
  src/Controller/Admin/GDPRDataController.php
  src/Controller/Admin/HelperController.php
  src/Controller/Admin/RulesController.php
  src/Controller/Admin/SegmentAssignmentController.php
  src/Controller/Admin/SettingsController.php
  src/Controller/Admin/TemplatesController.php
  src/Controller/Preview/ObjectPreviewController.php
  src/Controller/Report/TermSegmentBuilderController.php
  src/Controller/Rest/AbstractRestController.php
  src/Controller/Rest/Api/ActivitiesController.php
  src/Controller/Rest/Api/CustomersController.php
  src/Controller/Rest/Api/DeletionsController.php
  src/Controller/Rest/Api/SegmentGroupsController.php
  src/Controller/Rest/Api/SegmentsController.php
  src/Controller/Rest/Api/SegmentsOfCustomersController.php
  src/Controller/Rest/CrudHandlerController.php
  src/Controller/Rest/Mailchimp/WebhookController.php
  src/Newsletter/ProviderHandler/Mailchimp/UpdateFromMailchimpProcessor.php
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/RESTApi/Response.php
  src/Security/Authenticator/WebserviceAuthenticator.php
Labels: Task
