Repository pimcore/customer-data-framework, pull requests merged in 2023-02, with the labels that each got.

#406 [Task] Add pimcore 10 and 11 support for new menu creation
  src/Resources/public/css/pimcore.css
  src/Resources/public/js/startup.js
Labels: Improvement, Task

#414 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
  .github/ci/files/bin/console
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/public/.htaccess
Labels: sync

#415 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/config/system.yml
  .github/ci/files/public/.htaccess
Labels: sync

#416 Drop support for Pimcore 10
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  composer.json
  doc/02_Installation/01_Update.md
  src/ActivityStore/MariaDb.php
  src/ActivityStore/SqlActivityStore.php
  src/CustomReport/Adapter/TermSegmentBuilder.php
  src/CustomReport/Adapter/TermSegmentBuilderBase.php
  src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
  src/Installer.php
  src/Model/ActionTrigger/Rule/Dao.php
  src/Model/ActivityList/ActivityListInterface.php
  src/Model/Traits/DefaultUserawareCustomerTrait.php
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/Resources/config/custom_reports_legacy.yml
  src/Resources/sql/segmentAssignment/storedFunctionObject.sql
  src/Resources/sql/segmentAssignment/storedFunctionObject_Pimcore11.sql
  tests/_bootstrap.php
Labels: Task, BC-BREAK

#417 Keep ApplicationLogger Compatibility
  src/Controller/Rest/Mailchimp/WebhookController.php
  src/Installer.php
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/Traits/ApplicationLoggerAware.php
Labels: Task

#410 Updated the targeting and personalization namespace
  src/ActionTrigger/Event/TargetGroupAssigned.php
  src/Event/TargetingEventListener.php
  src/Installer.php
  src/Model/Activity/TargetGroupAssignActivity.php
  src/PimcoreCustomerManagementFrameworkBundle.php
  src/Resources/config/pimcore/config.yml
  src/Resources/config/services_events.yml
  src/Resources/public/js/pimcore/targeting/actions.js
  src/Resources/public/js/pimcore/targeting/conditions.js
  src/Resources/views/targeting/toolbar.html.twig
  src/SegmentManager/DefaultSegmentManager.php
  src/Targeting/ActionHandler/ApplyTargetGroupsFromSegments.php
  src/Targeting/ActionHandler/AssignTargetGroupAndSegment.php
  src/Targeting/ActionHandler/TrackActivity.php
  src/Targeting/ActionHandler/TrackSegment.php
  src/Targeting/Condition/CustomerIsLoggedIn.php
  src/Targeting/Condition/CustomerSegmentsHaveChanged.php
  src/Targeting/Condition/HasSegment.php
  src/Targeting/DataProvider/Customer.php
  src/Targeting/DataProvider/CustomerSegments.php
  src/Targeting/EventListener/ElementSegmentsListener.php
  src/Targeting/EventListener/TargetingToolbarListener.php
  src/Targeting/SegmentTracker.php
Labels: Task

#421 Fix PHP Stan
  phpstan-baseline.neon
  phpstan-lowest.neon
  src/Model/CustomerView/FilterDefinition.php
Labels: Bug

#418 fix(customermerger): fix activities merge
  src/CustomerMerger/DefaultCustomerMerger.php
Labels: Bug

#422 Adapt system.yml - related to https://github.com/pimcore/pimcore/pull/14276
  .github/ci/files/config/system.yml
Labels: sync

#419 fix(documentation): correct webhook url
  doc/24_NewsletterSync/README.md
Labels: Bug

#411 Remove unused OAuth config
  .github/ci/files/var/classes/DataObject/Customer.php
  .github/ci/files/var/classes/DataObject/Customer/Listing.php
  .github/ci/files/var/classes/DataObject/Objectbrick/Data/OAuth1Token.php
  .github/ci/files/var/classes/DataObject/Objectbrick/Data/OAuth2Token.php
  .github/ci/files/var/classes/DataObject/SsoIdentity.php
  .github/ci/files/var/classes/DataObject/SsoIdentity/Credentials.php
  .github/ci/files/var/classes/DataObject/SsoIdentity/Listing.php
  CHANGELOG.md
  doc/02_Installation/01_Update.md
  install/class_source/class_SsoIdentity_export.json
  install/class_source/optional/class_Customer_export.json
  install/objectbrick_source/objectbrick_OAuth1Token_export.json
  install/objectbrick_source/objectbrick_OAuth2Token_export.json
  phpstan.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
  src/Installer.php
  src/Model/AbstractSsoIdentity.php
  src/Model/OAuth/OAuth1TokenInterface.php
  src/Model/OAuth/OAuth2TokenInterface.php
  src/Model/OAuth/OAuthTokenInterface.php
  src/Model/Objectbrick/AbstractOAuth1Token.php
  src/Model/Objectbrick/AbstractOAuth2Token.php
  src/Model/SsoAwareCustomerInterface.php
  src/Model/SsoIdentityInterface.php
  src/Security/SsoIdentity/SsoIdentityServiceInterface.php
  stubs/AccountNotLinkedException.stub
  stubs/OAuthUtils.stub
Labels: Bug
