Repository pimcore/customer-data-framework, pull requests merged in 2024-01, with the labels that each got.

#523 Improper Access Control allows unprivileged user to access customers duplicates list
  src/Controller/Admin/DuplicatesController.php
Labels: Security

#524 Improper Access Control allows unprivileged user to access customers duplicates list - LTS
  src/Controller/Admin/DuplicatesController.php
Labels: Task, Security

#520 Added null check to confirm (new) customer objects have an id before …
  src/CustomerSaveManager/DefaultCustomerSaveManager.php
Labels: Bug

#525 [Bug]: Fix GDPR search-data-objects permission
  src/Controller/Admin/GDPRDataController.php
Labels: Bug, Security
