Repository pimcore/customer-data-framework, pull requests merged in 2024-04, with the labels that each got.

#530 Update cla checker
  .github/workflows/cla-check.yaml
Labels: Task

#533 Fix PhpStan
  phpstan-baseline.neon
  src/ActionTrigger/EventHandler/DefaultEventHandler.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/Controller/Admin/DuplicatesController.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
  src/RESTApi/ActivitiesHandler.php
  src/RESTApi/CustomersHandler.php
  src/RESTApi/SegmentGroupsHandler.php
  src/RESTApi/SegmentsHandler.php
  src/SegmentBuilder/AgeSegmentBuilder.php
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
Labels: Pimcore:ToDo

#534 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo

#532 Upgraded to PHP CS Fixer v3
  .github/workflows/php-cs-fixer.yaml
  .github/workflows/php-style.yml
  .gitignore
  .php-cs-fixer.dist.php
  .php_cs.dist
Labels: Pimcore:ToDo
