Repository pimcore/customer-data-framework, pull requests merged in 2025-04, with the labels that each got.

#561 Fix for permission issue
  src/Resources/public/js/ActivityView.js
Labels: Pimcore:ToDo

#579 [Bug]: Fix "No SELECT expressions given" when exporting
  src/Controller/Admin/CustomersController.php
Labels: Bug, Pimcore:ToDo

#580 [Phpstan]: Fix error about select
  phpstan-lowest.neon
  src/Controller/Admin/CustomersController.php
Labels: Bug

#582 [Bug]: Fix filter in activity view
  src/Controller/Admin/ActivitiesController.php
Labels: Bug, Pimcore:Priority

#583 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
  .github/workflows/codeception.yml
Labels: Task

#584 Fix codeception
  .github/workflows/codeception.yml
Labels: Task
