Repository pimcore/customer-data-framework, pull requests merged in 2025-02, with the labels that each got.

#557 [Bug]: Use parameters for joins in Customer Segment (#549)
  .github/workflows/static-analysis.yml
  composer.json
  src/CustomerList/Filter/CustomerSegment.php
  src/CustomerProvider/ObjectNamingScheme/DefaultObjectNamingScheme.php
Labels: Bug

#556 Use parameters for joins
  .github/workflows/static-analysis.yml
  src/CustomerList/Filter/CustomerSegment.php
  src/CustomerProvider/ObjectNamingScheme/DefaultObjectNamingScheme.php
Labels: Bug

#555 add nesbot/carbon to composer, adapt to new version
  composer.json
  src/CustomerView/Customer/Maintenance.php
  src/DataTransformer/Date/TimestampToAge.php
  src/Model/AbstractObjectActivity.php
  src/Model/Activity/GenericActivity.php
  src/Model/ActivityStoreEntry/DefaultActivityStoreEntry.php
  src/Newsletter/ProviderHandler/Mailchimp/CliSyncProcessor.php
  src/Newsletter/ProviderHandler/Mailchimp/MailChimpExportService.php
  tests/Model/Customer/CustomerListTest.php
Labels: Pimcore:ToDo, Internal

#564 [Task] Update workflows
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
Labels: Task, Pimcore:ToDo

#559 [Bugfix] Update Version in Installer
  src/Installer.php
Labels: Bug

#565 [Task] Add container extension
  src/PimcoreCustomerManagementFrameworkBundle.php
Labels: Task, Pimcore:ToDo
