Repository pimcore/customer-data-framework, pull requests merged in 2025-03, with the labels that each got.

#566 Support nesting customer objects again
  src/CustomerProvider/ObjectNamingScheme/DefaultObjectNamingScheme.php
Labels: Bug

#567 [Task] Remove BC Layer for DataObject Service (getVersionDependentDatabaseColumnName)
  src/ActionTrigger/Condition/CountActivities.php
  src/ActionTrigger/Condition/Customer.php
  src/ActionTrigger/EventHandler/DefaultEventHandler.php
  src/Controller/Admin/CustomersController.php
  src/Controller/Admin/DuplicatesController.php
  src/Controller/Admin/SegmentAssignmentController.php
  src/CustomerDuplicatesService/DefaultCustomerDuplicatesService.php
  src/CustomerList/Exporter/AbstractExporter.php
  src/CustomerList/Filter/CustomerSegment.php
  src/CustomerProvider/ObjectNamingScheme/DefaultObjectNamingScheme.php
  src/DependencyInjection/Configuration.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/Helper/Objects.php
  src/Listing/Filter/Permission.php
  src/Model/AbstractObjectActivity.php
  src/Newsletter/ProviderHandler/Mailchimp.php
  src/Newsletter/Queue/DefaultNewsletterQueue.php
  src/RESTApi/CustomersHandler.php
  src/RESTApi/SegmentGroupsHandler.php
  src/RESTApi/SegmentsHandler.php
  src/SegmentAssignment/QueryService/DefaultQueryService.php
  src/SegmentAssignment/QueueBuilder/DefaultQueueBuilder.php
  src/SegmentManager/DefaultSegmentManager.php
  src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php
  tests/Model/Customer/CustomerListTest.php
Labels: Task

#568 [Improvement]: Add support to Doctrine v4
  CHANGELOG.md
  composer.json
  src/ActivityStore/MariaDb.php
  src/Controller/Admin/ActivitiesController.php
  src/Controller/Admin/CustomersController.php
  src/CustomerList/Filter/SearchQuery.php
  src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
  src/Listing/Filter/AbstractFieldBetween.php
  src/Listing/Filter/AbstractFieldValue.php
  src/Listing/Filter/BoolCombinator.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
  src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
  src/Newsletter/ProviderHandler/Mailchimp.php
  tests/_support/Helper/Model.php
Labels: Improvement, Pimcore:Priority

#570 [Task]: Follow DBAL 4 support
  composer.json
Labels: Task, Pimcore:ToDo
