Repository pimcore/customer-data-framework, pull requests merged in 2025-01, with the labels that each got.

#547 [Bug]: Fix decline duplicates
  src/Controller/Admin/DuplicatesController.php
Labels: Bug, Pimcore:ToDo

#548 [Bug]: CMF Admin Customer List export id ambiguity
  src/Controller/Admin/CustomersController.php
Labels: Bug

#549 Use parameters for joins
  src/CustomerList/Filter/CustomerSegment.php
Labels: Security, Pimcore:Priority
